### ISSUE TITLE
Part of cassandra yet?

### ISSUE THREAD

**Issue by otto-dev** [bradfordcp/cassandra-tickler#3]
@bradfordcp You said in a talk from 2016 that there was a discussion to make this part of Cassandra. (Just saw it on YouTube). Did that end up happening? Cheers

**Comment by bradfordcp** [comment]
Not to my knowledge. There are other repair services out there like [DataStax's OpsCenter](https://www.datastax.com/products/datastax-opscenter) and [NodeSync](https://docs.datastax.com/en/dse/6.7/dse-admin/datastax_enterprise/config/aboutNodesync.html) along with [Reaper by The Last Pickle](https://thelastpickle.com/reaper.html)
